{
    'name': 'XE Currency Converter',
    'version': '12.0.1.0.0',
    'category': 'Accounting',
    'description': """Convert currency rate based on company currency by using xe.com platform""",
    'category': 'Accounting',
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    'maintainer': 'Cybrosys Techno Solutions',
    'depends': ['base', 'account'],
    'data': ['views/config_settings_views.xml',
             'views/service_cron.xml'],
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
