# -*- coding: utf-8 -*-
#############################################################################
#
#    Cybrosys Technologies Pvt. Ltd.
#
#    Copyright (C) 2026-TODAY Cybrosys Technologies(<https://www.cybrosys.com>)
#    Author: Cybrosys Techno Solutions(<https://www.cybrosys.com>)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
from odoo import models, fields, api, _


class AccountAnomalyRule(models.Model):
    """
    User-configurable detection rule for flagging suspicious accounting transactions
    based on custom criteria such as amount thresholds, account filters, partner filters, or keywords.
    """
    _name = 'account.anomaly.rule'
    _description = 'Anomaly Detection Rule'
    _order = 'sequence, name'

    name = fields.Char(
        string='Rule Name', required=True,
        help="Name or short summary of this detection rule.")
    sequence = fields.Integer(
        string='Sequence', default=10,
        help="Priority sequence used to order rule evaluation.")
    active = fields.Boolean(
        string='Active', default=True,
        help="Toggle to activate or deactivate this detection rule.")
    company_id = fields.Many2one(
        'res.company', string='Company', default=lambda self: self.env.company,
        help="Company to which this detection rule applies.")

    rule_type = fields.Selection([
        ('amount_threshold', 'Amount Threshold'),
        ('account_type', 'Account Type Pattern'),
        ('partner', 'Partner Rule'),
        ('keyword', 'Description Keyword'),
    ], string='Rule Type', required=True,
       help="Category of condition used by this rule to identify anomalies.")

    # Amount threshold fields
    min_amount = fields.Float(
        string='Minimum Amount',
        help="Minimum transaction amount to trigger amount threshold rule.")
    max_amount = fields.Float(
        string='Maximum Amount',
        help="Maximum transaction amount limit (set to 0 for no upper limit).")

    # Account filter
    account_ids = fields.Many2many(
        'account.account', string='Accounts to Monitor',
        help="Specific accounts monitored by this rule.")

    # Partner filter
    partner_ids = fields.Many2many(
        'res.partner', string='Partners to Monitor',
        help="Specific partners monitored by this rule.")

    # Keyword matching
    keywords = fields.Char(
        string='Keywords (comma-separated)',
        help='Flag transactions whose narration/reference contains these keywords')

    # Risk assignment
    risk_level = fields.Selection([
        ('critical', 'Critical'),
        ('high', 'High'),
        ('medium', 'Medium'),
        ('low', 'Low'),
    ], string='Risk Level', compute='_compute_risk_level', store=True, precompute=True, default='low', readonly=False, required=True,
       help="Assessed risk level automatically computed from the rule score.")

    alert_title = fields.Char(
        string='Alert Title Template',
        help="Template string used for the generated alert title.")
    description_template = fields.Text(
        string='Alert Description Template',
        help="Template string used for the generated alert description.")
    score = fields.Integer(
        string='Anomaly Score', default=50,
        help="Anomaly score (0-100) assigned to alerts generated by this rule.")

    @api.depends('score')
    def _compute_risk_level(self):
        """Compute risk level from rule score (0-30 Low, 31-60 Medium, 61-90 High, 91-100 Critical)."""
        for rule in self:
            score = rule.score or 0
            if score <= 30:
                rule.risk_level = 'low'
            elif score <= 60:
                rule.risk_level = 'medium'
            elif score <= 90:
                rule.risk_level = 'high'
            else:
                rule.risk_level = 'critical'

    hits_count = fields.Integer(
        string='Total Hits', compute='_compute_hits_count',
        help="Total number of anomaly alerts triggered by this rule.")

    @api.depends()
    def _compute_hits_count(self):
        """Compute total count of alert records generated by this rule."""
        alert_model = self.env['account.anomaly.alert']
        for rule in self:
            rule.hits_count = alert_model.search_count([
                ('alert_type', '=', 'manual'),
                ('ml_details', 'like', f'rule:{rule.id}'),
            ])
