from . import test_zk_machine
from . import test_zk_machine_attendance
from . import test_zk_report_daily_attendance
from . import test_zkattendance
from . import test_zkconnect
from . import test_zkconst
from . import test_zkdevice
from . import test_zkextendfmt
from . import test_zkextendoplog
from . import test_zkface
from . import test_zklib
from . import test_zkos
from . import test_zkpin
from . import test_zkplatform
from . import test_zkserialnumber
from . import test_zkssr
from . import test_zktime
from . import test_zkuser
from . import test_zkversion
from . import test_zkworkcode
