# -*- coding: utf-8 -*-
#############################################################################
#
#    Cybrosys Technologies Pvt. Ltd.
#
#    Copyright (C) 2026-TODAY Cybrosys Technologies (<https://www.cybrosys.com>).
#    Author: Cybrosys Techno Solutions (<https://www.cybrosys.com>)
#
#    This program is under the terms of the Odoo Proprietary License v1.0
#    (OPL-1). It is forbidden to publish, distribute, sublicense, or sell
#    copies of the Software or modified copies of the Software.
#
#    The above copyright notice and this permission notice must be included in
#    all copies or substantial portions of the Software.
#
#############################################################################

import json
import requests
import logging
from odoo import models, fields, api
from odoo.tools import html2plaintext

_logger = logging.getLogger(__name__)


class HelpdeskTicket(models.Model):
    _inherit = "helpdesk.ticket"

    sentiment_score = fields.Float("Raw Sentiment Score",
                                   tracking=True,
                                   help="The raw sentiment score generated by the AI, ranging from -1.0 "
                                        "(Highly Negative) to 1.0 (Highly Positive). A score of 0.0 "
                                        "indicates a perfectly neutral tone.")
    sentiment_percent = fields.Integer("Customer Mood (%)", compute="_compute_sentiment_percent",
                                       store=True,
                                       tracking=True,
                                       help="The AI sentiment score converted into a standard 0 to 100"
                                            " percentage scale. 0% represents maximum frustration, 50% is "
                                            "neutral, and 100% is extremely satisfied.")
    sentiment_human = fields.Char("Customer Mood", compute="_compute_sentiment_human", store=True,
                                  tracking=True,
                                  help="A human-readable label and emoji representing the customer's current emotional "
                                       "state, determined by the AI analysis.")

    risk_level = fields.Selection([
        ('low', 'Healthy'),
        ('medium', 'Attention Needed'),
        ('high', 'Critical')
    ], default="low", tracking=True,
        help="The calculated churn risk level of this specific ticket. 'Critical' tickets "
             "typically contain severe frustration and require immediate escalation.")

    is_high_risk = fields.Boolean("High Risk",
                                  help="A technical flag indicating if this ticket is currently "
                                       "classified as 'Critical'. Used behind the scenes for dashboard "
                                       "filtering and automated alerts.")

    @api.depends('sentiment_score')
    def _compute_sentiment_percent(self):
        """Converts the raw sentiment score (-1.0 to 1.0) into a 0-100 percentage scale."""
        for ticket in self:
            if ticket.sentiment_score is not False:
                ticket.sentiment_percent = int((ticket.sentiment_score + 1) * 50)
            else:
                ticket.sentiment_percent = 50

    @api.depends('sentiment_score')
    def _compute_sentiment_human(self):
        """Assigns a human-readable emotional label and emoji based on the raw sentiment score."""
        for ticket in self:
            score = ticket.sentiment_score or 0
            if score <= -0.6:
                ticket.sentiment_human = "Very Frustrated 🔴"
            elif score <= -0.2:
                ticket.sentiment_human = "Unhappy 🟠"
            elif score <= 0.2:
                ticket.sentiment_human = "Neutral 🟡"
            elif score <= 0.6:
                ticket.sentiment_human = "Satisfied 🟢"
            else:
                ticket.sentiment_human = "Very Happy 🟢"

    @api.model_create_multi
    def create(self, vals_list):
        """Overrides ticket creation to automatically run AI sentiment analysis on the initial ticket description."""
        tickets = super().create(vals_list)
        for ticket in tickets:
            try:
                if self.env['ir.config_parameter'].sudo().get_param(
                        'customer_success_sentiment_tracker.enable_ai') != 'True':
                    continue
                is_internal = False
                if ticket.partner_id:
                    if ticket.partner_id.user_ids and any(
                            not u.share for u in ticket.partner_id.user_ids):
                        is_internal = True
                else:
                    if ticket.create_uid and ticket.create_uid.id > 2 and not ticket.create_uid.share:
                        is_internal = True

                if not is_internal and ticket.description:
                    ticket._run_sentiment_analysis(ticket.description)
            except Exception as e:
                _logger.error("Error in AI Ticket Create: %s", e)
        return tickets

    def message_post(self, **kwargs):
        """Overrides chatter posting to intercept incoming customer replies and analyze their sentiment."""
        message = super().message_post(**kwargs)
        try:
            if self.env['ir.config_parameter'].sudo().get_param(
                    'customer_success_sentiment_tracker.enable_ai') != 'True':
                return message
            for ticket in self:
                if not message or message.message_type not in ('email', 'comment'):
                    continue
                if message.subtype_id and message.subtype_id.internal:
                    continue

                is_internal = False
                author = message.author_id
                if author:
                    if author.user_ids and any(not u.share for u in author.user_ids):
                        is_internal = True
                else:
                    if message.create_uid and message.create_uid.id > 2 and not message.create_uid.share:
                        is_internal = True

                if is_internal or not message.body:
                    continue
                ticket._run_sentiment_analysis(message.body)
        except Exception as e:
            _logger.error("Error in AI Message Post: %s", e)
        return message

    def _extract_json(self, content):
        """Safely extracts and parses a JSON dictionary from a raw string returned by the OpenAI API."""
        try:
            start = content.find('{')
            end = content.rfind('}')
            if start == -1 or end == -1: return None
            return json.loads(content[start:end + 1])
        except Exception as e:
            _logger.error("JSON parsing failed: %s", e)
            return None

    def _run_sentiment_analysis(self, body):
        """Sends the provided text to OpenAI for sentiment analysis and updates the ticket's scores accordingly."""
        _logger.info("=== Running sentiment analysis ===")
        config = self.env['ir.config_parameter'].sudo()
        _logger.info("AI Enabled: %s", config.get_param('customer_success_sentiment_tracker.enable_ai'))
        api_key = config.get_param('customer_success_sentiment_tracker.openai_api_key')
        model = config.get_param('customer_success_sentiment_tracker.model_id') or 'gpt-4o-mini'
        _logger.info("Model = %s", model)

        if not api_key: return
        text = html2plaintext(body)
        if not text.strip(): return

        prompt = f"""Analyze the sentiment of the following customer message.
        Return strictly raw JSON with no markdown formatting:
        {{"score": float between -1 and 1}}
        Message:
        {text}
        """

        try:
            response = requests.post(
                "https://api.openai.com/v1/chat/completions",
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                json={"model": model, "messages": [{"role": "user", "content": prompt}],
                      "temperature": 0.2,
                      "max_tokens": 50},
                timeout=20
            )

            _logger.info("Status Code: %s", response.status_code)
            _logger.info("Response: %s", response.text)

            if response.status_code != 200:
                return

            content = response.json()['choices'][0]['message']['content']
            _logger.info("AI returned: %s", content)

            result = self._extract_json(content)
            if not result:
                _logger.warning("Failed to extract JSON from OpenAI response: %s", response.json())
                return

            score = float(result.get("score", 0))
            risk = 'high' if score <= -0.6 else 'medium' if score <= -0.2 else 'low'

            _logger.info("Score = %s", score)
            self.write({
                'sentiment_score': score,
                'risk_level': risk,
                'is_high_risk': risk == 'high'
            })
            _logger.info("Record updated")

            if risk == 'high':
                self._create_high_risk_activity()

        except Exception as e:
            _logger.error("Sentiment analysis request failed: %s", e)

    def _create_high_risk_activity(self):
        """Schedules a high-priority To-Do activity for Helpdesk Managers when a ticket is flagged as Critical."""
        manager_group = self.env.ref('helpdesk.group_helpdesk_manager', raise_if_not_found=False)
        if not manager_group: return
        for manager in manager_group.user_ids:
            self.activity_schedule(
                'mail.mail_activity_data_todo',
                user_id=manager.id,
                summary="Critical Customer Detected",
                note="Customer sentiment classified as CRITICAL. Immediate attention required."
            )
