# -*- coding: utf-8 -*-
#############################################################################
#
#    Cybrosys Technologies Pvt. Ltd.
#
#    Copyright (C) 2026-TODAY Cybrosys Technologies(<https://www.cybrosys.com>)
#    Author: Cybrosys Techno Solutions(<https://www.cybrosys.com>)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
from odoo import models, fields


class AiImageGenerationLog(models.Model):
    """Stores audit logs for AI image generation requests and results."""
    _name = 'ai.image.generation.log'
    _description = 'AI Image Generation Log'
    _order = 'create_date desc'
    _rec_name = 'product_id'

    product_id = fields.Many2one(
        'product.template',
        string='Product',
        ondelete='set null',
        index=True,
    )
    user_id = fields.Many2one(
        'res.users',
        string='Generated By',
        default=lambda self: self.env.user,
        readonly=True,
    )
    # ── Use create_date (built-in) instead of a custom timestamp ──
    # create_date is automatically set by Odoo — no default needed
    prompt = fields.Text(string='Prompt Used', readonly=True)
    ai_provider = fields.Selection(
        selection=[
            ('openai', 'OpenAI DALL-E 3'),
            ('stability', 'Stability AI'),
            ('gemini', 'Google Gemini'),
        ],
        string='AI Provider',
        readonly=True,
    )
    image_style = fields.Selection(
        selection=[
            ('professional', 'Professional Product Photo'),
            ('lifestyle', 'Lifestyle / In Context'),
            ('minimal', 'Minimal / White Background'),
            ('artistic', 'Artistic / Creative'),
        ],
        string='Image Style',
        readonly=True,
    )
    status = fields.Selection(
        selection=[
            ('success', 'Success'),
            ('failed', 'Failed'),
            ('pending_approval', 'Pending Approval'),
        ],
        string='Status',
        default='success',
        readonly=True,
    )
    image_generated = fields.Binary(
        string='Generated Image',
        attachment=True,
    )
    image_applied = fields.Boolean(
        string='Applied to Product',
        default=False,
        readonly=True,
    )
    enhance_mode = fields.Boolean(
        string='Enhance Mode',
        default=False,
        readonly=True,
    )
    error_message = fields.Text(
        string='Error Message',
        readonly=True,
    )
    num_variants_requested = fields.Integer(
        string='Variants Requested',
        readonly=True,
    )
    image_size = fields.Char(
        string='Image Size',
        readonly=True,
    )
