# -*- coding: utf-8 -*-
###############################################################################
#
#    Cybrosys Technologies Pvt. Ltd.
#
#    Copyright (C) 2026-TODAY Cybrosys Technologies(<https://www.cybrosys.com>)
#    Author: Cybrosys Techno Solutions(<https://www.cybrosys.com>)
#
#    You can modify it under the terms of the GNU AFFERO
#    GENERAL PUBLIC LICENSE (AGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU AFFERO GENERAL PUBLIC LICENSE (AGPL v3) for more details.
#
#    You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
#    (AGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################
import logging
from odoo import models, fields, api

_logger = logging.getLogger(__name__)


class JtlFfnOrderSync(models.Model):
    """
    Links a confirmed Odoo sale.order to its counterpart in JTL-FFN.
    Handles:
      - Building and pushing the fulfillment order payload.
      - Storing FFN order ID for later tracking/return lookups.
      - Retry logic for transient failures.
    """
    _name        = 'jtl.ffn.order.sync'
    _description = 'JTL FFN Order Fulfillment Sync'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _rec_name    = 'ffn_order_id'

    config_id      = fields.Many2one(
        'jtl.ffn.config', string="FFN Profile", required=True, tracking=True,
        help="JTL FFN configuration profile used for fulfillment."
    )
    sale_order_id  = fields.Many2one(
        'sale.order', string="Sale Order", required=True, tracking=True,
        help="Odoo sale order sent to JTL FFN."
    )
    warehouse_id   = fields.Many2one(
        'jtl.ffn.warehouse', string="FFN Warehouse", tracking=True,
        help="Target JTL FFN warehouse assigned to fulfill this order."
    )

    ffn_order_id   = fields.Char(
        string="FFN Order ID", copy=False, tracking=True,
        help="Fulfillment order reference number generated by JTL FFN."
    )
    ffn_jfsku      = fields.Char(
        string="FFN JFSKU", copy=False, tracking=True,
        help="Comma-separated JFSKUs of products included in this fulfillment order."
    )
    push_state     = fields.Selection([
        ('pending',   'Pending'),
        ('sent',      'Sent to FFN'),
        ('confirmed', 'Confirmed by FFN'),
        ('shipped',   'Shipped'),
        ('error',     'Error'),
    ], default='pending', string="Push State", tracking=True,
        help="Status of order push to FFN (Pending, Sent, Confirmed, Shipped, Error).")
    push_error     = fields.Char(
        string="Last Error", copy=False, tracking=True,
        help="Error description if pushing order to FFN failed."
    )
    pushed_at      = fields.Datetime(
        string="Pushed At", readonly=True, tracking=True,
        help="Timestamp when the order was pushed to JTL FFN."
    )
    retry_count    = fields.Integer(
        string="Retry Count", default=0, tracking=True,
        help="Number of times pushing this order to JTL FFN was retried."
    )

    _sql_constraints = [
        ('unique_order_config',
         'unique(config_id, sale_order_id)',
         'This sale order is already registered for this FFN profile.'),
    ]

    # Maximum number of push attempts before giving up on an order permanently.
    MAX_RETRIES = 5

    def push_pending_orders(self, config):
        """Find all confirmed sale orders not yet sent and push them.

        Orders that have already failed MAX_RETRIES times are excluded so
        they don't flood the API or the logs on every cron run.
        """
        sent_order_ids = self.search([
            ('config_id',  '=', config.id),
            ('push_state', 'in', ['sent', 'confirmed', 'shipped']),
        ]).mapped('sale_order_id.id')

        # Also exclude permanently-failed orders (hit retry cap)
        exhausted_order_ids = self.search([
            ('config_id',   '=', config.id),
            ('push_state',  '=', 'error'),
            ('retry_count', '>=', self.MAX_RETRIES),
        ]).mapped('sale_order_id.id')

        orders = self.env['sale.order'].search([
            ('state', 'in', ['sale', 'done']),
            ('id',    'not in', sent_order_ids + exhausted_order_ids),
        ])
        pushed = 0
        for order in orders:
            with self.env.cr.savepoint():
                try:
                    self._push_order(config, order)
                    pushed += 1
                except Exception as exc:
                    _logger.warning("FFN order push failed for %s: %s", order.name, exc)
        return pushed

    def _push_order(self, config, sale_order):
        """Build and POST a single fulfillment order to FFN."""
        sync_rec = self.search([
            ('config_id',     '=', config.id),
            ('sale_order_id', '=', sale_order.id),
        ], limit=1)

        target_wh = self._resolve_warehouse(config, sale_order)
        if not target_wh:
            _logger.warning("FFN: order %s skipped — no FFN warehouse configured", sale_order.name)
            vals = {
                'config_id':     config.id,
                'sale_order_id': sale_order.id,
                'push_state':    'error',
                'push_error':    "Skipped: No FFN warehouse configured",
            }
            if sync_rec:
                vals['retry_count'] = sync_rec.retry_count + 1
                sync_rec.write(vals)
            else:
                vals['retry_count'] = 1
                self.create(vals)
            return

        items = []
        for idx, line in enumerate(sale_order.order_line.filtered(
            lambda l: l.product_id.type in ['product', 'consu']
            and l.product_id.default_code
        ), start=1):
            items.append({
                'outboundItemId': str(idx),
                'merchantSku':    line.product_id.default_code,
                'quantity':       float(line.product_uom_qty),
                'price':          line.price_unit,
                'name':           line.product_id.name,
            })

        if not items:
            _logger.info("FFN: order %s has no shippable lines — skipped", sale_order.name)
            vals = {
                'config_id':     config.id,
                'sale_order_id': sale_order.id,
                'push_state':    'error',
                'push_error':    "Skipped: No shippable product lines (storable/consumable with SKU)",
            }
            if sync_rec:
                vals['retry_count'] = sync_rec.retry_count + 1
                sync_rec.write(vals)
            else:
                vals['retry_count'] = 1
                self.create(vals)
            return

        try:
            partner = sale_order.partner_shipping_id
            name_parts = (partner.name or '').split(' ', 1)
            address = {
                'firstname': name_parts[0],
                'lastname':  name_parts[1] if len(name_parts) > 1 else '',
                'company':   partner.company_name or '',
                'street':    partner.street or '',
                'city':      partner.city or '',
                'zip':       partner.zip or '',
                'country':   partner.country_id.code if partner.country_id else '',
                'state':     partner.state_id.name if partner.state_id else '',
                'phone':     partner.phone or partner.mobile or '',
                'email':     partner.email or '',
            }
            if partner.street2:
                address['extraAddressLine'] = partner.street2

            payload = {
                'merchantOutboundNumber': sale_order.name,
                'warehouseId':            target_wh.ffn_warehouse_id,
                'currency':               sale_order.currency_id.name,
                'items':                  items,
                'shippingAddress':        address,
            }
            
            if config.fallback_shipping_method_id:
                payload['shippingMethodId'] = config.fallback_shipping_method_id
            if config.fallback_shipping_type:
                payload['shippingType'] = config.fallback_shipping_type

            if sale_order.note:
                payload['externalNote'] = sale_order.note[:4096]

            result = config._api_request('POST', '/v1/outbounds', json=payload)
            ffn_id = (
                result.get('outboundId')
                or result.get('fulfillmentOrderId')
                or result.get('id')
                or sale_order.name
            )

            prod_syncs = self.env['jtl.ffn.product.sync'].search([
                ('config_id', '=', config.id),
                ('product_id', 'in', sale_order.order_line.mapped('product_id').ids),
                ('ffn_product_id', '!=', False),
            ])
            jfskus = prod_syncs.mapped('ffn_product_id')
            jfsku_str = ",".join(jfskus) if jfskus else ''

            vals = {
                'config_id':     config.id,
                'sale_order_id': sale_order.id,
                'warehouse_id':  target_wh.id if target_wh else False,
                'ffn_order_id':  ffn_id,
                'ffn_jfsku':     jfsku_str,
                'push_state':    'sent',
                'push_error':    False,
                'pushed_at':     fields.Datetime.now(),
            }
            if sync_rec:
                sync_rec.write(vals)
            else:
                self.create(vals)

            _logger.info("FFN: order %s pushed → FFN ID %s", sale_order.name, ffn_id)

        except Exception as exc:
            err_msg = str(exc.args[0] if hasattr(exc, 'args') and exc.args else exc)
            vals = {
                'config_id':     config.id,
                'sale_order_id': sale_order.id,
                'warehouse_id':  target_wh.id if target_wh else False,
                'push_state':    'error',
                'push_error':    err_msg[:500],
                'pushed_at':     fields.Datetime.now(),
            }
            if sync_rec:
                vals['retry_count'] = sync_rec.retry_count + 1
                sync_rec.write(vals)
            else:
                vals['retry_count'] = 1
                self.create(vals)
            raise exc

    def _resolve_warehouse(self, config, sale_order):
        """Pick the best FFN warehouse for this order."""
        country = sale_order.partner_shipping_id.country_id
        for wh in config.warehouse_ids.filtered('active').sorted('sequence'):
            if country in wh.route_country_ids:
                return wh
        default = config.warehouse_ids.filtered(
            lambda w: w.active and w.is_default
        )
        return default[:1] if default else config.warehouse_ids[:1]

    @api.model
    def cron_push_orders(self):
        """Called by the scheduled action."""
        for config in self.env['jtl.ffn.config'].search([
            ('active', '=', True),
            ('sync_orders', '=', True),
        ]):
            self.push_pending_orders(config)

    def action_sync_all(self):
        self.cron_push_orders()
        return {
            'type': 'ir.actions.act_window',
            'name': 'Order Fulfillment Log',
            'res_model': 'jtl.ffn.order.sync',
            'view_mode': 'list,form',
            'target': 'current',
        }

