# -*- coding: utf-8 -*-
#############################################################################
#
#    Cybrosys Technologies Pvt. Ltd.
#
#    Copyright (C) 2026-TODAY Cybrosys Technologies(<https://www.cybrosys.com>)
#    Author: Cybrosys Techno Solutions (odoo@cybrosys.com)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <https://www.gnu.org/licenses/>.
#
#############################################################################
import logging
from datetime import timedelta

from dateutil.relativedelta import relativedelta
from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError


_logger = logging.getLogger(__name__)


class WmMonthlyBillingRun(models.Model):
    """Model to track monthly billing execution runs for customers on monthly consolidated billing."""
    _name = 'wm.monthly.billing.run'
    _description = 'Monthly Billing Run'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'create_date desc, id desc'

    name = fields.Char(
        string='Reference',
        required=True,
        copy=False,
        readonly=True,
        default=lambda self: _('New'),
    )
    period_start = fields.Date(string='Period Start', required=True, tracking=True)
    period_end = fields.Date(string='Period End', required=True, tracking=True)
    state = fields.Selection([
        ('draft', 'Draft'),
        ('done', 'Done'),
        ('error', 'Error'),
    ], string='Status', default='draft', tracking=True, copy=False)
    line_ids = fields.One2many('wm.monthly.billing.run.line', 'run_id', string='Run Lines', copy=False)
    partner_ids = fields.Many2many(
        'res.partner',
        'wm_monthly_billing_run_partner_rel',
        'run_id',
        'partner_id',
        string='Target Customers',
        help="Target customers for this monthly billing run. If empty, all monthly run customers are processed.",
    )
    invoice_ids = fields.One2many('account.move', 'billing_run_id', string='Invoices', copy=False)
    invoice_count = fields.Integer(string='Invoice Count', compute='_compute_invoice_count', store=True)
    error_message = fields.Text(string='Execution Log / Errors', copy=False)
    company_id = fields.Many2one('res.company', string='Company', required=True, default=lambda self: self.env.company)

    @api.depends('invoice_ids')
    def _compute_invoice_count(self):
        """
        Count the total account.move invoices generated by this billing run
        across all billing lines, shown on the billing run's Invoices smart
        button.
        """
        for run in self:
            run.invoice_count = len(run.invoice_ids)

    @api.model_create_multi
    def create(self, vals_list):
        """
        Override create to implement custom initialization and validation
        logic.
        """
        for vals in vals_list:
            if vals.get('name', _('New')) == _('New'):
                vals['name'] = self.env['ir.sequence'].next_by_code('wm.monthly.billing.run') or _('New')
        return super().create(vals_list)

    def write(self, vals):
        """
        Reset state to 'draft' if any data fields are modified while the
        billing run is in 'done' state.
        """
        ignore_fields = {
            'state', 'message_ids', 'activity_ids', 'message_follower_ids',
            'message_main_attachment_id', 'error_message', 'invoice_ids',
            'invoice_count',
        }
        if 'state' not in vals and any(field not in ignore_fields for field in vals):
            for run in self:
                if run.state == 'done':
                    vals = dict(vals, state='draft')
                    break
        return super().write(vals)

    @api.constrains('period_start', 'period_end')
    def _check_period_dates(self):
        """
        Validate that the billing period start date is earlier than the end
        date, and that the period does not overlap with any existing confirmed
        billing run.
        """
        for run in self:
            if run.period_start and run.period_end and run.period_end < run.period_start:
                raise ValidationError(_("Period End date cannot be earlier than Period Start date."))

    @api.model
    def _cron_run_monthly_billing(self):
        """
        Cron job to execute monthly billing for eligible customers.
        """
        today = fields.Date.today()
        # Scoped to partners assigned to 'monthly_run' billing mode
        partners = self.env['res.partner'].search([
            ('billing_mode', '=', 'monthly_run'),
        ])
        if not partners:
            _logger.info("Monthly Billing Cron: No partners found for monthly run billing mode.")
            return

        period_start = (today.replace(day=1) - relativedelta(months=1))
        period_end = today.replace(day=1) - timedelta(days=1)

        # Check if any billable orders exist for candidate partners before creating a run record
        billable_orders = self.env['wm.collection.order']._get_billable_orders(
            partner=partners,
            period_start=period_start,
            period_end=period_end,
        )
        if not billable_orders:
            _logger.info("Monthly Billing Cron: No billable collection orders found for period %s - %s.", period_start, period_end)
            return

        run = self.create({
            'period_start': period_start,
            'period_end': period_end,
        })
        run.action_run_billing(partner_ids=partners.ids)

    def _get_billable_orders(self, partner, period_start, period_end):
        """
        Find completed/signed collection orders for partner in period that have
        not been billed.
        """
        return self.env['wm.collection.order']._get_billable_orders(partner, period_start, period_end)

    def action_run_billing(self, partner_ids=None):
        """
        Execute monthly billing consolidation across targeted partners.
        """
        if not (self.env.user.has_group('wm_base.group_wm_finance') or self.env.user.has_group('wm_base.group_wm_admin') or self.env.is_admin()):
            raise UserError(_("Only Billing & Finance officers and Administrators can execute monthly billing runs."))

        for run in self:
            if run.state == 'done':
                raise UserError(_("This monthly billing run has already been completed."))

            if partner_ids:
                partners = self.env['res.partner'].browse(partner_ids)
            elif run.partner_ids:
                partners = run.partner_ids
            else:
                partners = self.env['res.partner'].search([('billing_mode', '=', 'monthly_run')])

            if not partners:
                run.write({
                    'state': 'error',
                    'error_message': _("No eligible partners were found for monthly run billing.")
                })
                continue

            created_invoices = self.env['account.move']
            log_messages = []
            has_error = False
            currency = run.company_id.currency_id or self.env.company.currency_id

            for partner in partners:
                orders = run._get_billable_orders(partner, run.period_start, run.period_end)
                if not orders:
                    log_messages.append(_("Partner '%s': No billable orders found in period.") % partner.display_name)
                    continue

                try:
                    with self.env.cr.savepoint():
                        # Prevent check-then-act race: acquire row-level lock on billable orders
                        self.env.cr.execute(
                            "SELECT id FROM wm_collection_order WHERE id IN %s AND billing_run_line_id IS NULL AND consolidated_invoice_id IS NULL FOR UPDATE SKIP LOCKED",
                            [tuple(orders.ids)]
                        )
                        locked_order_ids = [row[0] for row in self.env.cr.fetchall()]
                        if not locked_order_ids:
                            log_messages.append(_("Partner '%s': Orders already claimed by another concurrent billing run.") % partner.display_name)
                            continue

                        orders = orders.filtered(lambda o: o.id in locked_order_ids and not o.billing_run_line_id and not o.consolidated_invoice_id)
                        if not orders:
                            log_messages.append(_("Partner '%s': Orders already billed.") % partner.display_name)
                            continue

                        category_totals = {}
                        for order in orders:
                            for line in order.order_line_ids:
                                if not line.category_id:
                                    continue
                                cat = line.category_id
                                if cat not in category_totals:
                                    category_totals[cat] = {
                                        'weight': 0.0,
                                        'line_count': 0,
                                        'product': line.product_id or False,
                                    }
                                category_totals[cat]['weight'] += line.weight
                                category_totals[cat]['line_count'] += 1

                        if not category_totals:
                            log_messages.append(_("Partner '%s': Billable orders exist but have no category lines.") % partner.display_name)
                            continue

                        invoice_lines = []
                        order_date = run.period_end or fields.Date.today()
                        has_zero_price_warning = False

                        for category, data in category_totals.items():
                            rule = self.env['wm.collection.order']._get_billing_rule(category, partner, order_date)
                            cat_weight = data['weight']
                            data['line_count']

                            if rule:
                                billing_basis = getattr(rule, 'billing_basis', 'per_kg')
                                if billing_basis == 'flat_per_collection':
                                    # per_collection contract: fixed fee × collections
                                    # + overweight surcharge if cat_weight > max_weight * len(orders)
                                    flat_total = rule.price * len(orders)
                                    max_weight = getattr(rule, 'max_weight', 0.0) or 0.0
                                    overweight_price = getattr(rule, 'overweight_price', 0.0) or 0.0
                                    allowed_weight = max_weight * len(orders)
                                    overweight_surcharge = 0.0
                                    if allowed_weight and overweight_price and cat_weight > allowed_weight:
                                        overweight_kg = cat_weight - allowed_weight
                                        overweight_surcharge = (overweight_kg / 10.0) * overweight_price
                                    line_total = flat_total + overweight_surcharge
                                    quantity = float(len(orders)) if len(orders) > 0 else 1.0
                                    price_unit = currency.round(line_total / quantity)
                                    desc = _("%s — %d collections (%s to %s)") % (
                                        category.name, len(orders),
                                        run.period_start.strftime('%Y-%m-%d'), run.period_end.strftime('%Y-%m-%d')
                                    )
                                    if overweight_surcharge:
                                        desc += _(" (incl. overweight surcharge: %s)") % round(overweight_surcharge, 2)
                                elif billing_basis == 'hybrid':
                                    # hybrid: base fee per collection + overweight per 10 kg above included_weight * len(orders)
                                    base_total = rule.price * len(orders)
                                    included_weight = getattr(rule, 'included_weight', 0.0) or getattr(rule, 'min_weight', 0.0) or 0.0
                                    overweight_price = getattr(rule, 'overweight_price', 0.0) or getattr(rule, 'min_charge', 0.0) or 0.0
                                    allowed_weight = included_weight * len(orders)
                                    overweight_surcharge = 0.0
                                    if allowed_weight and overweight_price and cat_weight > allowed_weight:
                                        overage_kg = cat_weight - allowed_weight
                                        overweight_surcharge = (overage_kg / 10.0) * overweight_price
                                    line_total = base_total + overweight_surcharge
                                    quantity = float(len(orders)) if len(orders) > 0 else 1.0
                                    price_unit = currency.round(line_total / quantity)
                                    desc = _("%s — %d collections, %s kg (base: %s, overage: %s) (%s to %s)") % (
                                        category.name, len(orders), round(cat_weight, 2),
                                        round(base_total, 2), round(overweight_surcharge, 2),
                                        run.period_start.strftime('%Y-%m-%d'), run.period_end.strftime('%Y-%m-%d')
                                    )
                                else:
                                    # per_kg / category_rate / material
                                    min_wt = getattr(rule, 'min_weight', 0.0) or 0.0
                                    weight_to_bill = max(cat_weight, min_wt) if min_wt else cat_weight
                                    line_total = weight_to_bill * rule.price
                                    min_charge = getattr(rule, 'min_charge', 0.0) or 0.0
                                    if min_charge and line_total < min_charge:
                                        line_total = min_charge
                                    quantity = cat_weight if cat_weight > 0 else 1.0
                                    price_unit = currency.round(line_total / quantity)
                                    desc = _("%s — %d collections, %s kg (%s to %s)") % (
                                        category.name, len(orders), round(cat_weight, 2),
                                        run.period_start.strftime('%Y-%m-%d'), run.period_end.strftime('%Y-%m-%d')
                                    )
                            else:
                                fallback_price = category.price or 0.0
                                if data['product'] and data['product'].list_price:
                                    fallback_price = data['product'].list_price
                                if fallback_price <= 0.0:
                                    has_zero_price_warning = True
                                    log_messages.append(_("WARNING: Partner '%s', Category '%s' priced at 0.00 (unconfigured rate card/pricing rule).") % (partner.display_name, category.name))
                                quantity = cat_weight if cat_weight > 0 else 1.0
                                price_unit = currency.round(fallback_price)
                                desc = _("%s — %d collections, %s kg (%s to %s)") % (
                                    category.name, len(orders), round(cat_weight, 2),
                                    run.period_start.strftime('%Y-%m-%d'), run.period_end.strftime('%Y-%m-%d')
                                )

                            invoice_lines.append((0, 0, {
                                'product_id': data['product'].id if data['product'] else False,
                                'name': desc,
                                'quantity': quantity,
                                'price_unit': price_unit,
                            }))

                        invoice = self.env['account.move'].sudo().create({
                            'move_type': 'out_invoice',
                            'partner_id': partner.id,
                            'company_id': run.company_id.id,
                            'invoice_date': run.period_end or fields.Date.today(),
                            'ref': run.name,
                            'billing_run_id': run.id,
                            'invoice_line_ids': invoice_lines,
                        })

                        run_line = self.env['wm.monthly.billing.run.line'].sudo().create({
                            'run_id': run.id,
                            'partner_id': partner.id,
                            'collection_order_ids': [(6, 0, orders.ids)],
                            'invoice_id': invoice.id,
                            'total_amount': invoice.amount_total,
                            'state': 'billed',
                            'has_zero_price_warning': has_zero_price_warning,
                        })

                        orders.sudo().write({'billing_run_line_id': run_line.id})
                        created_invoices |= invoice
                        log_messages.append(_("Partner '%s': Successfully generated invoice %s for %d order(s), total %s.") % (
                            partner.display_name, invoice.name or invoice.id, len(orders), invoice.amount_total
                        ))

                except Exception as e:
                    has_error = True
                    _logger.error("Monthly billing error for partner %s: %s", partner.display_name, e, exc_info=True)
                    err_msg = str(e)
                    log_messages.append(_("ERROR Partner '%s': %s") % (partner.display_name, err_msg))
                    self.env['wm.monthly.billing.run.line'].create({
                        'run_id': run.id,
                        'partner_id': partner.id,
                        'collection_order_ids': [(6, 0, orders.ids)],
                        'state': 'error',
                        'error_message': err_msg,
                    })

            final_state = 'done' if not has_error else 'error'
            run.write({
                'state': final_state,
                'error_message': '\n'.join(log_messages),
            })

    def action_view_invoices(self):
        """
        View generated invoices for this monthly billing run.
        """
        self.ensure_one()
        invoices = self.invoice_ids
        action = {
            'name': _('Generated Invoices'),
            'type': 'ir.actions.act_window',
            'res_model': 'account.move',
            'domain': [('id', 'in', invoices.ids)],
            'context': {'default_move_type': 'out_invoice'},
        }
        if len(invoices) == 1:
            action['view_mode'] = 'form'
            action['res_id'] = invoices.id
        else:
            action['view_mode'] = 'list,form'
        return action


class WmMonthlyBillingRunLine(models.Model):
    """Line model tracking individual partner results in a monthly billing run."""
    _name = 'wm.monthly.billing.run.line'
    _description = 'Monthly Billing Run Line'

    run_id = fields.Many2one('wm.monthly.billing.run', string='Billing Run', required=True, ondelete='cascade')
    partner_id = fields.Many2one('res.partner', string='Partner', required=True)
    collection_order_ids = fields.Many2many('wm.collection.order', string='Collection Orders')
    invoice_id = fields.Many2one('account.move', string='Invoice')
    total_amount = fields.Float(string='Total Amount', digits=(16, 2))
    state = fields.Selection([
        ('draft', 'Draft'),
        ('billed', 'Billed'),
        ('error', 'Error'),
    ], string='Status', default='draft', required=True)
    has_zero_price_warning = fields.Boolean(string='Zero Price Warning', default=False)
    error_message = fields.Text(string='Error Message')
