# -*- coding: utf-8 -*-
#############################################################################
#
#    Cybrosys Technologies Pvt. Ltd.
#
#    Copyright (C) 2026-TODAY Cybrosys Technologies(<https://www.cybrosys.com>)
#    Author: Cybrosys Techno Solutions (odoo@cybrosys.com)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <https://www.gnu.org/licenses/>.
#
#############################################################################
{
    'name': 'Waste Management Collection',
    'version': '19.0.1.0.0',
    'category': 'Operations/Waste Management',
    'summary': 'Waste Management Collection & Inventory (merged)',
    'description': "Collection order lifecycle, collection points, route planning, missed-collection workflow, waste batch management, sorting, batch inspection, valuation reports, and stock integration.",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Technologies Pvt. Ltd.',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': [
        'wm_base',
        'mail',
        'portal',
        'fleet',
        'account',
        'base_geolocalize',
        'survey',
        'stock',
        'stock_account',
        'uom',
    ],
    'external_dependencies': {
        'python': ['requests', 'openpyxl'],
    },
    'data': [
        'security/inventory_security.xml',
        'security/wm_collection_security.xml',
        'security/ir.model.access.csv',
        'data/enable_storage_locations.xml',
        'data/inventory_ir_config_parameter_data.xml',
        'data/inventory_ir_sequence_data.xml',
        'data/stock_location_data.xml',
        'data/ir_sequence_data.xml',
        'data/ir_config_parameter_data.xml',
        'data/missed_reason_data.xml',
        'data/missed_collection_mail_template.xml',
        'data/missed_collection_cron_data.xml',
        'data/schedule_cron_data.xml',
        'data/route_automation_cron_data.xml',
        'data/collection_order_signature_template_data.xml',
        'data/survey_data.xml',
        'data/pre_trip_checklist_data.xml',
        'data/post_trip_checklist_data.xml',
        'data/container_data.xml',
        'report/waste_batch_label.xml',
        'report/waste_valuation_report.xml',
        'report/waste_inspection_report.xml',
        'reports/collection_order_report.xml',
        'reports/collection_order_report_template.xml',
        'reports/route_sheet_actions.xml',
        'reports/route_sheet_template.xml',
        'reports/vehicle_inspection_checklist_actions.xml',
        'reports/vehicle_inspection_checklist_template.xml',
        'views/waste_batch_views.xml',
        'views/waste_batch_collection_ext_views.xml',
        'views/waste_batch_inspection_views.xml',
        'views/waste_batch_wizard_views.xml',
        'views/waste_valuation_wizard_views.xml',
        'views/waste_material_sort_config_views.xml',
        'views/waste_category_sort_config_views.xml',
        'views/wm_batch_aging_report_views.xml',
        'views/res_config_settings_inventory_views.xml',
        'wizard/map_view_config_wizard_views.xml',
        'views/wm_service_zone_views.xml',
        'views/res_config_settings_views.xml',
        'views/wm_collection_order_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/wm_collection_point_views.xml',
        'views/wm_route_views.xml',
        'views/wm_schedule_views.xml',
        'views/wm_vehicle_maintenance_checklist_views.xml',
        'views/wm_driver_shift_views.xml',
        'views/survey_user_input_views.xml',
        'views/wm_fleet_expiry_report_views.xml',
        'views/wm_maintenance_history_report_views.xml',
        'views/wm_collection_report_views.xml',
        'views/wm_route_efficiency_report_views.xml',
        'views/wm_driver_performance_report_views.xml',
        'wizard/wm_missed_collection_report_wizard_views.xml',
        'views/wm_missed_collection_views.xml',
        'views/wm_missed_reason_views.xml',
        'wizard/wm_mark_missed_wizard_views.xml',
        'reports/wm_missed_collection_report_actions.xml',
        'reports/wm_missed_collection_report_templates.xml',
        'wizard/wm_collection_order_report_wizard_views.xml',
        'wizard/wm_change_driver_wizard_views.xml',
        'reports/wm_collection_order_summary_report_actions.xml',
        'reports/wm_collection_order_summary_report_templates.xml',
        'views/wm_missed_collection_report_views.xml',
        'views/menu_views.xml',
        'views/menuitems.xml',
        'views/inventory_menu.xml',
    ],
    'demo': [
        'demo/demo_container_types.xml',
        'demo/demo_waste_batches.xml',
        'demo/demo_batch_inspections.xml',
        'demo/demo_sort_config.xml',
        'demo/demo_collection_data.xml',
        'demo/demo_zone_data.xml',
        'demo/demo_checklists.xml',
        'demo/demo_driver_shifts.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'wm_collection/static/src/js/wm_route_map.js',
            'wm_collection/static/src/xml/wm_route_map.xml',
            'wm_collection/static/src/scss/wm_route_map.scss',
            'wm_collection/static/src/js/cog_menu_print.js',
            'wm_collection/static/lib/leaflet/leaflet.css',
            'wm_collection/static/lib/leaflet/leaflet.js',
            'wm_collection/static/src/scss/map_view.scss',
            'wm_collection/static/src/js/map_arch_parser.js',
            'wm_collection/static/src/js/map_model.js',
            'wm_collection/static/src/js/map_controller.js',
            'wm_collection/static/src/js/map_renderer.js',
            'wm_collection/static/src/js/map_view.js',
            'wm_collection/static/src/xml/map_view.xml',
        ],
    },
    'post_init_hook': 'post_init_hook',
    'images': ['static/description/banner.jpg'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': True,
}
