# -*- coding: utf-8 -*-
################################################################################
#
#    Cybrosys Technologies Pvt. Ltd.
#
#    Copyright (C) 2024-TODAY Cybrosys Technologies(<https://www.cybrosys.com>).
#    Author: Afra MP (odoo@cybrosys.com)
#
#    You can modify it under the terms of the GNU AFFERO
#    GENERAL PUBLIC LICENSE (AGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU AFFERO GENERAL PUBLIC LICENSE (AGPL v3) for more details.
#
#    You should have received a copy of the GNU AFFERO GENERAL PUBLIC LICENSE
#    (AGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
{
    'name': "Sales Team Access Controls",
    'version': '17.0.1.0.0',
    'category': 'Sales',
    'summary': """Provides access control for Sales Team members and leaders""",
    'description': """This module comes with a feature that empowers the 
    sales team to manage access control for Sale Quotations, Sale Orders, 
    CRM Leads, Sales Teams, and Contacts based on Team Leader and Team Member 
    roles. This feature enhances data security by granting team leaders full 
    access to all data generated by their team members. However, team members 
    are limited to accessing only their own data. This functionality ensures 
    data security while providing relevant information to users based on 
    their designated roles.""",
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['crm', 'sale_management'],
    'data': [
        'security/sales_team_access_controls_security.xml',
    ],
    'images': ['static/description/banner.jpg'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
