# -*- coding: utf-8 -*-
#############################################################################
#
#    Cybrosys Technologies Pvt. Ltd.
#
#    Copyright (C) 2026-TODAY Cybrosys Technologies(<https://www.cybrosys.com>)
#    Author: Cybrosys Techno Solutions(<https://www.cybrosys.com>)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
import json
import os
import re
from odoo import http
from odoo.osv import expression
from odoo.http import request
from odoo.modules.module import get_module_resource

_CSS_PARAM = 'backend_theme_infinito.dynamic_css'
_CSS_FILE = os.path.join(
    os.path.dirname(os.path.realpath(__file__)),
    '..', 'static', 'src', 'css', 'dynamic_styles.css'
)


def _write_css_file(css):
    try:
        with open(_CSS_FILE, 'w') as f:
            f.write(css)
    except Exception:
        pass


def _read_css_file():
    try:
        with open(_CSS_FILE, 'r') as f:
            return f.read()
    except Exception:
        return ''


def _minify_css_string(css):
    css = re.sub(r'/\*[\s\S]*?\*/', "", css)
    css = re.sub(r'url\((["\'])([^)]*)\1\)', r'url(\2)', css)
    css = re.sub(r'\s+', ' ', css)
    css = re.sub(r'#([0-9a-f])\1([0-9a-f])\2([0-9a-f])\3(\s|;)', r'#\1\2\3\4', css)
    css = re.sub(r':\s*0(\.\d+([cm]m|e[mx]|in|p[ctx]))\s*;', r':\1;', css)
    rules = re.findall(r'([^{]+){([^}]*)}', css)
    selectors_list = []
    css_values = {}
    for rule in rules:
        selector = rule[0]
        content = rule[1]
        if selector not in selectors_list:
            selectors_list.append(selector)
            css_values[selector] = content
        else:
            css_values[selector] += content
    out = '/* Generated by Theme Infinito */\n'
    for selector in selectors_list:
        dict_rule = {}
        for r in css_values[selector].split(';'):
            if r:
                parts = r.split(':')
                if len(parts) == 2:
                    dict_rule[parts[0].strip()] = parts[1]
        out += selector + '{'
        for prop, val in dict_rule.items():
            if prop != 'pointer-events':
                if '!important' not in val:
                    out += prop + ':' + val + ' !important;'
                else:
                    out += prop + ':' + val + ';'
        out += '}'
    return out


class ThemeStudio(http.Controller):
    """
    Controller class for managing themes in a web application.

    This controller handles requests related to managing themes, such as
    applying themes, customizing themes, and saving theme settings.
    """

    @http.route(['/theme_studio/save_styles'], type="json")
    def save_styles(self, kwargs):
        """
        Save dynamic styles to a CSS file.

        Parameters:
            kwargs (dict): A dictionary containing the changed_styles and
            object_class.

        Returns:
            bool: True if the styles are successfully saved, otherwise False.

        This function takes the changed_styles and object_class from the
        kwargs dictionary and saves them to a CSS file. It appends the styles
        to an existing file or creates a new file if it doesn't exist.
        After saving the styles, it minifies the CSS file.

        Example:
            To save styles for a specific object class:

            ```python
            from my_theme_module import save_styles

            save_styles({
                'changed_styles': {
                    'color': 'red',
                    'font-size': '16px'
                },
                'object_class': 'my-object'
            })
            ```
        """
        changed_styles_str = kwargs.get('changed_styles', '{}')
        object_class = kwargs.get('object_class', '')
        changed_styles = json.loads(changed_styles_str)
        IrConfigParam = request.env['ir.config_parameter'].sudo()
        css = IrConfigParam.get_param(_CSS_PARAM, default='')
        css += '\n.' + object_class + ' {\n'
        for prop, val in changed_styles.items():
            css += '\t' + prop + ': ' + val + ';\n'
        css += '}\n'
        minified = _minify_css_string(css)
        IrConfigParam.set_param(_CSS_PARAM, minified)
        _write_css_file(minified)
        return True

    @http.route(['/theme_studio/get_current_style'], type="json")
    def get_current_style(self, kwargs):
        """
       Retrieve the current styles for a given CSS selector.

       Parameters:
           kwargs (dict): A dictionary containing the 'selector' key
           specifying the CSS selector.

       Returns:
           list or bool: A list of style properties and values for the
           specified selector, or False if the selector is not found.

       This function reads the CSS file containing dynamic styles and
       searches for the specified CSS selector. If the selector is found,
       it returns a list of style properties and values associated with that
       selector. Each style property-value pair is represented as a list
       containing the property and its corresponding value.
       If the selector is not found,it returns False.

       Example:
           To retrieve the current styles for a specific CSS selector:

           ```python
           from my_theme_module import get_current_style

           current_styles = get_current_style({
               'selector': '.my-selector'
           })
           print(current_styles)
           # Output: [['color', 'red'], ['font-size', '16px']]
           ```
       """
        selector = kwargs.get('selector', '')
        IrConfigParam = request.env['ir.config_parameter'].sudo()
        css = IrConfigParam.get_param(_CSS_PARAM, default='')
        css = re.sub(r'/\*[\s\S]*?\*/', "", css)
        css = re.sub(r'url\((["\'])([^)]*)\1\)', r'url(\2)', css)
        css = re.sub(r'\s+', ' ', css)
        css = re.sub(r'#([0-9a-f])\1([\da-f])\2([0-9a-f])\3(\s|;)', r'#\1\2\3\4', css)
        css = re.sub(r':\s*0(\.\d+([cm]m|e[mx]|in|p[ctx]))\s*;', r':\1;', css)
        rules = re.findall(r'([^{]+){([^}]*)}', css)
        for rule in rules:
            selector_now = rule[0]
            content = rule[1]
            if selector == selector_now.strip():
                result = []
                for c in content.split(';'):
                    parts = c.split(':')
                    if parts[0] != '' and len(parts) > 1:
                        result.append([parts[0], parts[1].strip().replace('!important', '')])
                return result
        return False

    @http.route(['/theme_studio/reset_to_default'], type="json")
    def reset_to_default(self):
        """
        Reset dynamic styles to default.

        Returns:
            bool: True if the styles are successfully reset, otherwise False.

        This function clears the content of the CSS file containing
        dynamic styles, effectively resetting all styles to their default
        values.

        Example:
            To reset dynamic styles to default:

            ```python
            from my_theme_module import reset_to_default

            reset_to_default()
            ```
        """
        request.env['ir.config_parameter'].sudo().set_param(_CSS_PARAM, '')
        _write_css_file('/* This Styles are generated automatically by Theme Studio */\n')
        return True

    @http.route(['/backend_theme_infinito/dynamic_styles.css'], type='http', auth='public')
    def serve_dynamic_styles(self):
        # Prefer the physical file (Odoo 17 compatible); fall back to DB param.
        css = _read_css_file() or \
              request.env['ir.config_parameter'].sudo().get_param(_CSS_PARAM, default='')
        return request.make_response(
            css,
            headers=[
                ('Content-Type', 'text/css; charset=utf-8'),
                ('Cache-Control', 'no-cache, no-store, must-revalidate'),
            ]
        )

    @http.route(['/theme_studio/set_advanced_data'], type="json")
    def set_advanced_data(self, args):
        """
        Set advanced theme configuration data.

        Parameters:
            args (list): A list containing a dictionary with the advanced
            theme configuration values.

        Returns:
            bool: True if the configuration data is successfully set,
            otherwise False.

        This function sets advanced theme configuration data based on the
        provided dictionary of values. It updates the configuration
        parameters in the database accordingly.

        Example:
            To set advanced theme configuration data:
    ```python
            from my_theme_module import set_advanced_data

            data = [{
                'vals': {
                    'sidebar': True,
                    'fullscreen': False,
                    'sidebarIcon': True,
                    'sidebarName': True,
                    'sidebarCompany': False,
                    'sidebarUser': True,
                    'recentApps': False,
                    'fullScreenApp': True,
                    'infinitoRtl': False,
                    'infinitoDark': True,
                    'infinitoDarkMode': 'dark',
                    'infinitoBookmark': True
                }
            }]

            set_advanced_data(data)
    ```
        """
        if args and 'vals' in args[0]:
            vals = args[0]['vals']

            # Get the ir.config_parameter object
            IrConfigParam = request.env['ir.config_parameter'].sudo()

            # ADD THE MISSING PARAMETERS:
            IrConfigParam.set_param('backend_theme_infinito.is_user_edit', vals.get('userEdit', False))
            IrConfigParam.set_param('backend_theme_infinito.loader_class', vals.get('loaderClass', 'default'))
            IrConfigParam.set_param('backend_theme_infinito.dark_start', vals.get('infinitoDarkStart', 19.0))
            IrConfigParam.set_param('backend_theme_infinito.dark_end', vals.get('infinitoDarkEnd', 5.0))

            # EXISTING PARAMETERS:
            IrConfigParam.set_param('backend_theme_infinito.is_sidebar_enabled', vals['sidebar'])
            IrConfigParam.set_param('backend_theme_infinito.is_fullscreen_enabled', vals['fullscreen'])
            IrConfigParam.set_param('backend_theme_infinito.is_sidebar_icon', vals['sidebarIcon'])
            IrConfigParam.set_param('backend_theme_infinito.is_sidebar_name', vals['sidebarName'])
            IrConfigParam.set_param('backend_theme_infinito.is_sidebar_company', vals['sidebarCompany'])
            IrConfigParam.set_param('backend_theme_infinito.is_sidebar_user', vals['sidebarUser'])
            IrConfigParam.set_param('backend_theme_infinito.is_recent_apps', vals['recentApps'])
            IrConfigParam.set_param('backend_theme_infinito.is_fullscreen_app', vals['fullScreenApp'])
            IrConfigParam.set_param('backend_theme_infinito.is_rtl', vals['infinitoRtl'])
            IrConfigParam.set_param('backend_theme_infinito.is_dark', vals['infinitoDark'])
            IrConfigParam.set_param('backend_theme_infinito.dark_mode', vals['infinitoDarkMode'])
            IrConfigParam.set_param('backend_theme_infinito.is_menu_bookmark', vals['infinitoBookmark'])

            return True
        return False



    @http.route(['/theme_studio/set_advanced_data_user'], type="json")
    def set_advanced_data_user(self, args):
        """
        Set advanced theme configuration data for the current user.

        Parameters:
            args (list): A list containing a dictionary with the advanced
            theme configuration values.

        Returns:
            bool: True if the configuration data is successfully set for the
            user, otherwise False.

        This function sets advanced theme configuration data for the current
        user based on the provided dictionary of values. It updates the
        corresponding fields in the user record accordingly.

        Example:
            To set advanced theme configuration data for the current user:

            ```python
            from my_theme_module import set_advanced_data_user

            data = [{
                'vals': {
                    'sidebar': True,
                    'fullscreen': False,
                    'sidebarIcon': True,
                    'sidebarName': True,
                    'sidebarCompany': False,
                    'sidebarUser': True,
                    'recentApps': False,
                    'fullScreenApp': True,
                    'infinitoRtl': False,
                    'infinitoDark': True,
                    'infinitoDarkMode': 'dark',
                    'infinitoBookmark': True,
                    'loaderClass': 'custom-loader'
                }
            }]

            set_advanced_data_user(data)
            ```
        """
        if args and 'vals' in args[0]:
            vals = args[0]['vals']
            request.env.user.write({
                'is_sidebar_enabled': vals['sidebar'],
                'is_fullscreen_enabled': vals['fullscreen'],
                'is_sidebar_icon': vals['sidebarIcon'],
                'is_sidebar_name': vals['sidebarName'],
                'is_sidebar_company': vals['sidebarCompany'],
                'is_sidebar_user': vals['sidebarUser'],
                'is_recent_apps': vals['recentApps'],
                'is_fullscreen_app': vals['fullScreenApp'],
                'is_rtl': vals['infinitoRtl'],
                'is_dark': vals['infinitoDark'],
                'dark_mode': vals['infinitoDarkMode'],
                'is_menu_bookmark': vals['infinitoBookmark'],
                'loader_class': vals['loaderClass']
            })

            return True

    @http.route(['/theme_studio/add_recent_app'], type="json")
    def add_recent_app(self, args):
        """
        Add a recent application to the user's recent apps list.

        Parameters:
            args (list): A list containing a dictionary with the 'appId' key
            specifying the ID of the application.

        Returns:
            bool: True if the recent app is successfully added, otherwise False.

        This function adds a recent application to the user's recent apps list
        based on the provided application ID. It checks if the provided
        arguments are valid and if the user has already reached the maximum
        limit of recent apps (5), it removes the oldest one before adding the
        new one.

        Example:
            To add a recent application with ID 123 to the user's recent apps
            list:

            ```python
            from my_theme_module import add_recent_app

            add_recent_app([{'appId': 123}])
            ```
        """
        if args and isinstance(args, list) and len(args) > 0:
            app_id = args[0].get('appId')
            if app_id is not None:
                app_id = int(app_id)
            else:
                app_id = 0
        else:
            app_id = 0

        recent_app = request.env['recent.apps'].sudo()
        exist = recent_app.search([
            ('app_id', '=', app_id),
            ('user_id', '=', request.env.user.id)
        ])
        exist.unlink() if exist else None
        total_recent = recent_app.search(
            [('user_id', '=', request.env.user.id)])
        if len(total_recent) > 4:
            total_recent[0].unlink()
        recent_app.create({
            'app_id': app_id,
            'user_id': request.env.user.id
        })

    @http.route(['/theme_studio/get_recent_apps'], type="json")
    def get_recent_apps(self):
        """
       Retrieve the list of recent applications for the current user.

       Returns:
           list: A list of dictionaries containing the recent applications'
           information,
               or an empty list if no recent apps are found.

       This function retrieves the list of recent applications for the current
       user from the database. It returns a list of dictionaries containing the
       information of each recent application, such as its ID, name, and other
       relevant details.

       Example:
           To retrieve the list of recent applications for the current user:

           ```python
           from my_theme_module import get_recent_apps

           recent_apps = get_recent_apps()
           print(recent_apps)
           ```
       """
        recent_app = request.env['recent.apps'].sudo()
        return recent_app.search_read([
            ('user_id', '=', request.env.user.id)
        ])

    @http.route(['/theme_studio/add_menu_bookmarks'], type="json")
    def add_menu_bookmarks(self, args):
        """
        Add a menu bookmark for the current user.

        Parameters:
            args (dict): A dictionary containing the menu data including
            'actionId' and 'menuUrl'.

        Returns:
            bool: True if the menu bookmark is successfully added, otherwise
            False.

        This function adds a menu bookmark for the current user based on the
        provided
        menu data. It extracts the action ID and URL from the menu data and
        creates a
        new menu bookmark record in the database.

        Example:
            To add a menu bookmark with action ID 123 and URL '/dashboard' for
            the current user:

            ```python
            from my_theme_module import add_menu_bookmarks

            menu_data = {
                'actionId': 123,
                'menuUrl': '/dashboard'
            }
            add_menu_bookmarks({'menu': menu_data})
            ```
        """
        menu_data = args.get('menu', {})
        action_id = menu_data.get('actionId')
        menu_id = menu_data.get('menuId')
        user_id = request.env.user.id
        url = menu_data.get('menuUrl')
        name = menu_data.get('name')
        menu = request.env['ir.ui.menu'].sudo()
        menu_record = menu.browse(int(menu_id)) if menu_id else menu.browse()
        if menu_record and not menu_record.exists():
            menu_record = menu.browse()
        if not name and menu_record:
            name = menu_record.name
        if not name and action_id:
            action = request.env['ir.actions.actions'].sudo().browse(int(action_id))
            if action.exists():
                name = action.name
        menu_bookmark = request.env['infinito.menu.bookmark'].sudo()
        menu_domain = [('menu_id', '=', menu_record.id)] if menu_record else []
        url_domain = [('url', '=', url)] if url else []
        if menu_domain and url_domain:
            domain = expression.AND([
                [('user_id', '=', user_id)],
                expression.OR([menu_domain, url_domain]),
            ])
        elif menu_domain:
            domain = [('user_id', '=', user_id)] + menu_domain
        elif url_domain:
            domain = [('user_id', '=', user_id)] + url_domain
        elif action_id:
            domain = [('user_id', '=', user_id), ('action_id', '=', int(action_id))]
        else:
            return False
        existing_bookmark = menu_bookmark.search(domain, limit=1)
        if existing_bookmark:
            existing_bookmark.write({
                'action_id': int(action_id) if action_id else existing_bookmark.action_id.id,
                'menu_id': menu_record.id if menu_record else existing_bookmark.menu_id.id,
                'url': url or existing_bookmark.url,
                'name': name or existing_bookmark.name or 'Bookmark',
            })
            return True
        menu_bookmark.create({
            'action_id': int(action_id) if action_id else False,
            'menu_id': menu_record.id if menu_record else False,
            'user_id': user_id,
            'url': url,
            'name': name or 'Bookmark',
        })
        return True

    @http.route(['/theme_studio/remove_menu_bookmarks'], type="json")
    def remove_menu_bookmarks(self, args):
        """
        Remove a menu bookmark for the current user.

        Parameters:
            args (dict): A dictionary containing the menu data including
            'actionId'.

        Returns:
            bool: True if the menu bookmark is successfully removed,
            otherwise False.

        This function removes a menu bookmark for the current user based on
        the provided
        action ID. It searches for the menu bookmark record in the database and
        deletes
        it if found.

        Example:
            To remove a menu bookmark with action ID 123 for the current user:

            ```python
            from my_theme_module import remove_menu_bookmarks

            menu_data = {
                'actionId': 123
            }
            remove_menu_bookmarks({'menu': menu_data})
            ```
        """
        menu_data = args.get('menu', {})
        action_id = menu_data.get('actionId')
        menu_id = menu_data.get('menuId')
        url = menu_data.get('menuUrl')
        user_id = request.env.user.id
        if menu_id and url:
            domain = expression.AND([
                [('user_id', '=', user_id)],
                expression.OR([
                    [('menu_id', '=', int(menu_id))],
                    [('url', '=', url)],
                ]),
            ])
        elif menu_id:
            domain = [('user_id', '=', user_id), ('menu_id', '=', int(menu_id))]
        elif url:
            domain = [('user_id', '=', user_id), ('url', '=', url)]
        elif action_id:
            domain = [('user_id', '=', user_id), ('action_id', '=', int(action_id))]
        else:
            return False
        menu_bookmark = request.env['infinito.menu.bookmark'].sudo().search(domain)
        if menu_bookmark:
            menu_bookmark.unlink()
        return True

    @http.route(['/theme_studio/get_presets'], type="json")
    def get_presets(self):
        """
        Retrieve the list of available presets.

        Returns:
            list: A list of dictionaries containing the available presets.

        This function reads the presets data from a JSON file and returns
        it as a list of dictionaries.
        Each dictionary in the list represents a preset with
        its configuration details.

        Example:
            To retrieve the list of available presets:

            ```python
            from my_theme_module import get_presets

            presets = get_presets()
            print(presets)
            ```
        """
        file_path = get_module_resource("backend_theme_infinito", "static", "src", "json", "presets.json")
        file = open(file_path, 'r')
        presets = json.load(file)
        return presets
