# -*- coding: utf-8 -*-
{
    'name': 'Top/Least Selling Product Report',
    'version': '12.0.1.0.0',
    'summary': 'Top Selling and Least Selling Product Reports',
    'description': 'Top Selling Products,Fast Moving Products,Most Selling Products,Top Growing Products,Least Selling Products,',
    'author': 'Cybrosys Techno solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['base','sale_management','stock','sale'],
    'category': 'Sale',
    'demo': [],
    'data': ['wizard/top_selling_wizard.xml',
             'report/top_selling_report.xml',
             'report/top_selling_report_template.xml'],
    'installable': True,
    'images': ['static/description/banner.png'],
    'qweb': [],
    'license': 'AGPL-3',
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,
}
