# -- coding: utf-8 --
#############################################################################
#
#    Cybrosys Technologies Pvt. Ltd.
#
#    Copyright (C) 2026-TODAY Cybrosys Technologies(<https://www.cybrosys.com>)
#    Author: Cybrosys Techno Solutions(<https://www.cybrosys.com>)
#
#    You can modify it under the terms of the GNU LESSER
#    GENERAL PUBLIC LICENSE (LGPL v3), Version 3.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU LESSER GENERAL PUBLIC LICENSE (LGPL v3) for more details.
#
#    You should have received a copy of the GNU LESSER GENERAL PUBLIC LICENSE
#    (LGPL v3) along with this program.
#    If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
import math
import logging
from datetime import date, timedelta
from odoo import api, fields, models, _

_logger = logging.getLogger(__name__)

RISK_LEVELS = [
    ('low', 'Low Risk'),
    ('medium', 'Medium Risk'),
    ('high', 'High Risk'),
    ('critical', 'Critical Risk'),
]

RISK_COLORS = {
    'low':      '#28a745',
    'medium':   '#ffc107',
    'high':     '#fd7e14',
    'critical': '#dc3545',
}


class PaymentRiskScore(models.Model):
    """
    Core model for AI-powered late payment prediction.
    Data collection is done here in Python; scoring and reasoning are
    delegated to the Google Gemini AI via payment.risk.ai.service.
    """
    _name = 'payment.risk.score'
    _description = 'AI-Powered Customer Payment Risk Score'
    _order = 'score desc, write_date desc'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _rec_name = 'partner_id'

    partner_id = fields.Many2one(
        'res.partner', string='Customer', required=True,
        ondelete='cascade', index=True, help='Customer for whom the payment risk score is calculated.')
    company_id = fields.Many2one(
        'res.company', string='Company',
        default=lambda self: self.env.company, help='Company for which the payment risk score is generated.')
    currency_id = fields.Many2one(
        'res.currency', related='company_id.currency_id', store=True, help='Currency used for all monetary values in this risk analysis.')
    # Overall score
    score = fields.Float(
        string='Risk Score', digits=(5, 2),
        help='0-100. Higher score = higher late payment risk. Set by Google Gemini AI.')
    risk_level = fields.Selection(
        RISK_LEVELS, string='Risk Level', compute='_compute_risk_level', store=True,
        group_expand='_expand_risk_level',
        help='Categorized risk level derived from the overall payment risk score.')
    risk_color = fields.Char(
        string='Risk Color', compute='_compute_risk_level', store=True)
    # AI output fields
    ai_backend = fields.Char(
        string='AI Backend Used', readonly=True,
        help='Which AI backend generated this score (ollama, groq, openrouter, huggingface).')
    ai_powered = fields.Boolean(
        string='AI Scored', default=False, readonly=True,
        help='True if this score was generated by Google Gemini AI.')
    is_gemini_configured = fields.Boolean(
        string='Gemini Configured', compute='_compute_is_gemini_configured')
    ai_reasoning = fields.Text(
        string='AI Reasoning', readonly=True,
        help="Google Gemini's explanation of the key risk drivers.")
    followup_suggestion = fields.Text(
        string='Follow-up Action', readonly=True,
        help='AI-generated action steps for the finance team.')
    followup_email = fields.Text(
        string='AI-Drafted Follow-up Email', readonly=True,
        help='Ready-to-send email body drafted by Google Gemini.')
    # Sub-scores (returned by AI)
    delay_score      = fields.Float(string='Delay Score (max 30)',       digits=(5, 2), help='Score contribution based on average delay in customer payments.')
    overdue_score    = fields.Float(string='Overdue Score (max 25)',      digits=(5, 2), help='Score contribution based on the amount and frequency of overdue invoices.')
    consistency_score= fields.Float(string='Consistency Score (max 15)', digits=(5, 2), help='Score reflecting the consistency of the customer’s payment behavior.')
    recency_score    = fields.Float(string='Recency Score (max 15)',      digits=(5, 2), help='Score based on how recent the customer’s payment activity is.')
    volume_score     = fields.Float(string='Volume Score (max 10)',       digits=(5, 2), help='Score contribution based on the volume of invoices and payments.')
    trend_score      = fields.Float(string='Trend Score (+-5)',           digits=(5, 2), help='Score adjustment based on improving or worsening payment trends.')
    # Raw statistics
    total_invoices       = fields.Integer(string='Total Invoices Analysed', help='Total number of invoices used to calculate the payment risk score.')
    paid_on_time         = fields.Integer(string='Paid On Time', help='Number of invoices paid on or before the due date.')
    paid_late            = fields.Integer(string='Paid Late', help='Number of invoices paid after the due date.')
    avg_delay_days       = fields.Float(string='Avg Payment Delay (days)', digits=(6, 1), help='Average number of days payments are delayed beyond the due date.')
    max_delay_days       = fields.Float(string='Max Delay (days)',          digits=(6, 1), help='Maximum number of days a payment was delayed.')
    overdue_ratio        = fields.Float(string='Overdue Ratio (%)',         digits=(5, 2), help='Percentage of invoices that were paid late.')
    currently_overdue    = fields.Integer(string='Currently Overdue Invoices', help='Number of invoices that are currently overdue.')
    total_overdue_amount = fields.Monetary(
        string='Total Overdue Amount', currency_field='currency_id', help='Total outstanding amount from invoices that are currently overdue.')
    suggested_credit_limit = fields.Monetary(
        string='AI Suggested Credit Limit', currency_field='currency_id', help='Recommended credit limit for the customer based on payment behavior.')
    last_payment_date    = fields.Date(string='Last Payment Date', help='Date of the most recent payment received from this customer.')
    days_since_last_payment = fields.Integer(
        string='Days Since Last Payment',
        compute='_compute_days_since_payment', store=True, help='Number of days since the customer’s last recorded payment.')
    # Metadata
    last_computed = fields.Datetime(string='Last Computed', readonly=True, help='Date and time when the payment risk score was last calculated.')
    notes = fields.Text(string='Internal Notes', help='Additional internal comments or observations regarding this customer’s payment behavior.')
    _sql_constraints = [
        ('unique_partner_company', 'UNIQUE(partner_id, company_id)',
         'A risk score already exists for this customer in this company.'),
    ]

    @api.depends('score')
    def _compute_risk_level(self):
        """
        Compute the qualitative risk level and display color based on the
        calculated payment risk score.
        """
        for rec in self:
            s = rec.score or 0
            if s < 25:   rec.risk_level = 'low'
            elif s < 50: rec.risk_level = 'medium'
            elif s < 75: rec.risk_level = 'high'
            else:        rec.risk_level = 'critical'
            rec.risk_color = RISK_COLORS.get(rec.risk_level, '#6c757d')

    @api.model
    def _expand_risk_level(self, *args, **kwargs):
        return [key for key, val in RISK_LEVELS]

    def _compute_is_gemini_configured(self):
        """
        Determine whether the Google Gemini API key is configured in system
        parameters for AI-based scoring.
        """
        api_key = (
            self.env['ir.config_parameter'].sudo()
            .get_param('predict_late_payment.gemini_api_key', default=''))
        for rec in self:
            rec.is_gemini_configured = bool(api_key)

    @api.depends('last_payment_date')
    def _compute_days_since_payment(self):
        """
        Compute the number of days since the customer's last recorded payment.
        """
        today = date.today()
        for rec in self:
            rec.days_since_last_payment = (
                (today - rec.last_payment_date).days if rec.last_payment_date else 0)

    def _collect_invoice_stats(self, partner):
        """
        Collect invoice and payment statistics for the given partner.

        This method gathers historical invoice data such as payment delays,
        overdue invoices, payment trends, and invoice volumes which are used
        as input for the AI risk scoring engine.
        """
        today = date.today()
        company = self.env.company
        invoices = self.env['account.move'].search([
            ('partner_id', '=', partner.id),
            ('move_type', '=', 'out_invoice'),
            ('state', '=', 'posted'),
            ('company_id', '=', company.id),
        ], order='invoice_date asc')
        if not invoices:
            return None
        paid_invs = invoices.filtered(
            lambda m: m.payment_state in ('paid', 'in_payment'))
        overdue_invs = invoices.filtered(
            lambda m: m.payment_state not in ('paid', 'in_payment', 'reversed', 'cancelled')
                      and m.invoice_date_due and m.invoice_date_due < today)
        delays = []
        paid_history = []
        for inv in sorted(paid_invs, key=lambda x: x.invoice_date or date.min, reverse=True):
            pay_date = inv._get_last_payment_date()
            if pay_date and inv.invoice_date_due:
                delta = (pay_date - inv.invoice_date_due).days
                delays.append(delta)
                paid_history.append({
                    'name': inv.name,
                    'due_date': inv.invoice_date_due.isoformat(),
                    'paid_date': pay_date.isoformat(),
                    'delay_days': delta,
                    'amount': inv.amount_total,
                })
        avg_delay = sum(delays) / len(delays) if delays else 0
        max_delay = max(delays, default=0)
        std_dev = 0.0
        if len(delays) >= 2:
            variance = sum((d - avg_delay) ** 2 for d in delays) / len(delays)
            std_dev = math.sqrt(variance)
        overdue_ratio = (len(overdue_invs) / len(invoices) * 100) if invoices else 0
        cutoff_6m  = today - timedelta(days=180)
        cutoff_12m = today - timedelta(days=360)
        recent_delays = []
        old_delays = []
        for inv, d in zip(
            sorted(paid_invs, key=lambda x: x.invoice_date or date.min),
            delays
        ):
            if inv.invoice_date:
                if inv.invoice_date >= cutoff_6m:
                    recent_delays.append(d)
                elif inv.invoice_date >= cutoff_12m:
                    old_delays.append(d)
        recent_avg  = sum(recent_delays) / len(recent_delays) if recent_delays else avg_delay
        old_avg     = sum(old_delays) / len(old_delays)       if old_delays    else avg_delay
        trend_delta = recent_avg - old_avg
        pay_dates = [inv._get_last_payment_date() for inv in paid_invs
                     if inv._get_last_payment_date()]
        last_pay_date = max(pay_dates) if pay_dates else None
        overdue_list = [{
            'name': inv.name,
            'due_date': inv.invoice_date_due.isoformat(),
            'amount': abs(inv.amount_residual_signed),
            'days_overdue': (today - inv.invoice_date_due).days,
        } for inv in overdue_invs]
        total_overdue_amount = sum(abs(inv.amount_residual_signed) for inv in overdue_invs)
        avg_invoice_amount   = sum(inv.amount_total for inv in invoices) / len(invoices)
        first_invoice_date = (
            min(inv.invoice_date for inv in invoices if inv.invoice_date).isoformat()
            if any(inv.invoice_date for inv in invoices) else 'Unknown'
        )
        return {
            'total_invoices':       len(invoices),
            'paid_on_time':         sum(1 for d in delays if d <= 0),
            'paid_late':            sum(1 for d in delays if d > 0),
            'avg_delay_days':       round(avg_delay, 1),
            'max_delay_days':       round(max_delay, 1),
            'std_dev_delays':       round(std_dev, 1),
            'overdue_ratio':        round(overdue_ratio, 2),
            'currently_overdue':    len(overdue_invs),
            'total_overdue_amount': round(total_overdue_amount, 2),
            'avg_invoice_amount':   round(avg_invoice_amount, 2),
            'recent_total':         len(recent_delays),
            'recent_avg_delay':     round(recent_avg, 1),
            'trend_delta':          round(trend_delta, 1),
            'paid_invoice_history': paid_history,
            'overdue_invoices':     overdue_list,
            'first_invoice_date':   first_invoice_date,
            'last_payment_date':    last_pay_date,
        }

    def _compute_score_for_partner(self, partner):
        """
        Compute the payment risk score for a specific partner.

        Collects invoice statistics and sends them to the AI service
        to generate the final risk score and recommendations.
        """
        stats = self._collect_invoice_stats(partner)
        if stats is None:
            return self._no_history_values(partner)
        ai_result = self.env['payment.risk.ai.service'].analyse_customer(partner, stats)
        last_pay_date = stats['last_payment_date']
        return {
            'partner_id':             partner.id,
            'company_id':             self.env.company.id,
            'score':                  round(ai_result.get('score', 50), 2),
            'delay_score':            round(ai_result.get('delay_score', 0), 2),
            'overdue_score':          round(ai_result.get('overdue_score', 0), 2),
            'consistency_score':      round(ai_result.get('consistency_score', 0), 2),
            'recency_score':          round(ai_result.get('recency_score', 0), 2),
            'volume_score':           round(ai_result.get('volume_score', 0), 2),
            'trend_score':            round(ai_result.get('trend_score', 0), 2),
            'suggested_credit_limit': round(ai_result.get('suggested_credit_limit', 0), 2),
            'ai_powered':             ai_result.get('ai_powered', False),
            'ai_backend':             ai_result.get('ai_backend', ''),
            'ai_reasoning':           ai_result.get('ai_reasoning', ''),
            'followup_suggestion':    ai_result.get('followup_suggestion', ''),
            'followup_email':         ai_result.get('followup_email', ''),
            'total_invoices':         stats['total_invoices'],
            'paid_on_time':           stats['paid_on_time'],
            'paid_late':              stats['paid_late'],
            'avg_delay_days':         stats['avg_delay_days'],
            'max_delay_days':         stats['max_delay_days'],
            'overdue_ratio':          stats['overdue_ratio'],
            'currently_overdue':      stats['currently_overdue'],
            'total_overdue_amount':   stats['total_overdue_amount'],
            'last_payment_date':      last_pay_date,
            'last_computed':          fields.Datetime.now(),
        }

    def _no_history_values(self, partner):
        """
        Return default scoring values for partners without invoice history.
        """
        return {
            'partner_id':             partner.id,
            'company_id':             self.env.company.id,
            'score':                  0.0,
            'delay_score':            0.0, 'overdue_score':     0.0,
            'consistency_score':      0.0, 'recency_score':     0.0,
            'volume_score':           0.0, 'trend_score':       0.0,
            'suggested_credit_limit': 0.0,
            'ai_powered':             False,
            'ai_reasoning':           _('No invoice history available for this customer.'),
            'followup_suggestion':    _('Create invoices to start building a payment risk profile.'),
            'followup_email':         '',
            'total_invoices':         0, 'paid_on_time': 0, 'paid_late': 0,
            'avg_delay_days':         0.0, 'max_delay_days': 0.0,
            'overdue_ratio':          0.0, 'currently_overdue': 0,
            'total_overdue_amount':   0.0, 'last_payment_date': False,
            'last_computed':          fields.Datetime.now(),
        }

    @api.model
    def compute_for_partner(self, partner_id):
        """
        Compute or update the payment risk score record for a given partner.
        """
        partner = self.env['res.partner'].browse(partner_id)
        values  = self._compute_score_for_partner(partner)
        existing = self.search([
            ('partner_id', '=', partner_id),
            ('company_id', '=', self.env.company.id),
        ], limit=1)
        if existing:
            existing.write(values)
            return existing
        return self.create(values)

    @api.model
    def compute_all_partners(self):
        """Compute risk scores for all active customers. Returns count of scored partners."""
        partners = self.env['res.partner'].search([
            ('customer_rank', '>', 0), ('active', '=', True)])
        scored = 0
        for partner in partners:
            try:
                self.compute_for_partner(partner.id)
                scored += 1
            except Exception as e:
                _logger.error("Risk score failed for %s: %s", partner.name, e)
        return scored

    @api.model
    def action_compute_all_partners(self):
        """Server action entry point — returns a proper notification, never a UserError."""
        scored = self.compute_all_partners()
        if scored == 0:
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('No Customers Found'),
                    'message': _('No active customers with invoices were found to score.'),
                    'sticky': False,
                    'type': 'warning',
                },
            }
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': _('Risk Scores Updated'),
                'message': _('Payment risk scores have been recomputed for %d customer(s).') % scored,
                'sticky': False,
                'type': 'success',
            },
        }

    def action_compute_score(self):
        """
        Manually trigger recalculation of the payment risk score for
        the selected partner.
        """
        for rec in self:
            self.compute_for_partner(rec.partner_id.id)
        # Check the last record in the loop for configuration status feedback
        # (Assuming all records in the current set share the same config environment)
        if self and self[-1].ai_powered:
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('AI Score Updated'),
                    'message': _('Google Gemini AI has recalculated the payment risk score.'),
                    'sticky': False, 'type': 'success',
                },
            }
        else:
            return {
                'type': 'ir.actions.client',
                'tag': 'display_notification',
                'params': {
                    'title': _('Statistical Fallback Used'),
                    'message': _('Gemini not configured. Score computed using statistical rules. See AI Reasoning for details.'),
                    'sticky': False, 'type': 'warning',
                },
            }

    def action_send_followup(self):
        """
        Open the follow-up wizard with AI-generated communication
        for the selected partner.
        """
        self.ensure_one()
        message = self.followup_email or self.followup_suggestion or ''
        return {
            'type': 'ir.actions.act_window',
            'name': _('Send AI Follow-up'),
            'res_model': 'send.followup.wizard',
            'view_mode': 'form',
            'target': 'new',
            'context': {
                'default_partner_id':   self.partner_id.id,
                'default_risk_score_id': self.id,
                'default_message': '<p>%s</p>' % message.replace('\n', '<br/>'),
            },
        }

    def action_test_ai_connection(self):
        """Redirect to actual Gemini test action."""
        return self.env['res.config.settings'].action_test_gemini_connection()
